import { useState } from "react";
import { MapContainer,ImageOverlay,GeoJSON } from "react-leaflet";
const API="http://127.0.0.1:8000";
export default function Dashboard({result,onReset}){
 const [layers,setLayers]=useState({parcels:true,buildings:true,roads:true});
 const [selected,setSelected]=useState(null);
 const [review,setReview]=useState({});
 const c={parcels:result.parcels.features.length,buildings:result.buildings.features.length,roads:result.roads.features.length,issues:result.validation.issues.length};
 const toggle=k=>setLayers({...layers,[k]:!layers[k]});
 const mark=status=>{if(selected){const id=selected.properties.parcel_id||selected.properties.building_id||selected.properties.road_id;setReview({...review,[id]:status});}};
 const exportFile=()=>window.open(API+"/analysis/"+result.analysis_id+"/export","_blank");
 const status=selected&&review[selected.properties.parcel_id||selected.properties.building_id||selected.properties.road_id];
 return <main className="dashboard"><header className="topbar"><div><div className="brand">Sahi<span>Naksha</span></div><small>{result.analysis_mode==="opencv"?"AI feature extraction completed":"Demo fallback used — verify results"}</small></div><div className="actions"><button className="secondary-button" onClick={exportFile}>Export GeoJSON</button><button className="secondary-button" onClick={onReset}>New Analysis</button></div></header><section className="summary-grid"><div><b>{c.parcels}</b><span>Parcel Candidates</span></div><div><b>{c.buildings}</b><span>Buildings</span></div><div><b>{c.roads}</b><span>Road Features</span></div><div><b>{c.issues}</b><span>Validation Issues</span></div></section><section className="workspace"><aside className="sidebar"><h3>Layers</h3>{Object.keys(layers).map(k=><label key={k} className="toggle"><input type="checkbox" checked={layers[k]} onChange={()=>toggle(k)}/>{k}</label>)}<hr/><h3>Human Review</h3>{selected?<><div className="details">{Object.entries(selected.properties).map(([k,v])=><div key={k}><span>{k.replaceAll("_"," ")}</span><b>{String(v)}</b></div>)}</div><div className="review-buttons"><button onClick={()=>mark("Approved")}>Approve</button><button onClick={()=>mark("Needs Review")}>Review</button><button onClick={()=>mark("Rejected")}>Reject</button></div>{status&&<p className={"review-status "+status.toLowerCase().replaceAll(" ","-")}>{status}</p>}</>:<p className="muted">Click a feature, inspect it, then record a review decision.</p>}<hr/><h3>Validation</h3><p className="muted">{c.issues?c.issues+" issue(s) require review.":"No geometry issues detected."}</p></aside><div className="map-wrap"><MapContainer crs={undefined} center={[50,50]} zoom={1} style={{height:"100%",width:"100%"}}><ImageOverlay url={result.original_image_url} bounds={[[0,0],[100,100]]} opacity={0.65}/>{layers.parcels&&<GeoJSON data={result.parcels} style={{color:"#34d399",weight:2,fillOpacity:.18}} onEachFeature={(f,l)=>l.on({click:()=>setSelected(f)})}/>} {layers.buildings&&<GeoJSON data={result.buildings} style={{color:"#60a5fa",weight:2,fillOpacity:.35}} onEachFeature={(f,l)=>l.on({click:()=>setSelected(f)})}/>} {layers.roads&&<GeoJSON data={result.roads} style={{color:"#f59e0b",weight:5}} onEachFeature={(f,l)=>l.on({click:()=>setSelected(f)})}/>}</MapContainer><div className="map-note">AI-generated candidates require human verification.</div></div></section></main>;
}